"""
Generate Word doc reports from GCS JSON results and email them.

Gathers all topic JSONs from the last 7 days, creates a Word doc per topic,
and emails each one.

Usage:
    python scripts/generate_reports.py
    python scripts/generate_reports.py --days 14
"""
import argparse
import json
import os
import re
import sys
import tempfile
from datetime import datetime, timedelta
from pathlib import Path
from typing import Dict, List, Tuple

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, PROJECT_ROOT)

from dotenv import load_dotenv
load_dotenv(os.path.join(PROJECT_ROOT, ".env"))

from clients.gcs_client import GCSClient
from clients.db_client import DBClient
from clients.email_client import EmailClient
from clients.inoreader import ArticleItem
from summarize.report_summarizer import ReportSummarizer


def list_recent_results(gcs: GCSClient, days_back: int = 7) -> Dict[str, List[str]]:
    """List all result JSONs from the last N days, grouped by topic.
    
    Returns:
        Dict mapping topic name to list of blob paths
    """
    cutoff = datetime.utcnow() - timedelta(days=days_back)
    
    # List all blobs in results/
    blobs = gcs._bucket.list_blobs(prefix="results/")
    
    results_by_topic: Dict[str, List[str]] = {}
    
    for blob in blobs:
        # Parse blob name: results/{topic}_{dd_mm_yyyy}.json
        match = re.match(r"results/(.+)_(\d{2}_\d{2}_\d{4})\.json$", blob.name)
        if not match:
            continue
        
        topic = match.group(1)
        date_str = match.group(2)
        
        try:
            blob_date = datetime.strptime(date_str, "%d_%m_%Y")
            if blob_date >= cutoff:
                if topic not in results_by_topic:
                    results_by_topic[topic] = []
                results_by_topic[topic].append(blob.name)
        except ValueError:
            continue
    
    return results_by_topic


def load_articles_from_gcs(gcs: GCSClient, blob_paths: List[str]) -> List[ArticleItem]:
    """Download and parse articles from multiple GCS JSON files."""
    all_articles = []
    seen_ids = set()
    
    for blob_path in blob_paths:
        try:
            data = gcs.download_result(blob_path)
            for article_dict in data.get("articles", []):
                # Deduplicate by item_id
                item_id = article_dict.get("item_id")
                if item_id and item_id in seen_ids:
                    continue
                seen_ids.add(item_id)
                
                # Convert dict back to ArticleItem
                article = ArticleItem.from_dict(article_dict)
                all_articles.append(article)
        except Exception as e:
            print(f"      ⚠ Failed to load {blob_path}: {e}")
    
    return all_articles


def generate_topic_report(
    summarizer: ReportSummarizer,
    gcs: GCSClient,
    topic: str,
    articles: List[ArticleItem],
    start_date: datetime,
    end_date: datetime,
    temp_dir: Path,
) -> Tuple[Path, str]:
    """Generate Word doc report for a topic and upload to GCS.
    
    Returns:
        Tuple of (local temp path, GCS blob path)
    """
    # Format filename: summary_topic_startdate_enddate.docx
    start_str = start_date.strftime("%Y%m%d")
    end_str = end_date.strftime("%Y%m%d")
    safe_topic = re.sub(r"[^\w\-]", "_", topic)
    filename = f"summary_{safe_topic}_{start_str}_{end_str}.docx"
    local_path = temp_dir / filename
    
    title = f"{topic} - Regulatory Intelligence Briefing"
    
    print(f"\n   Generating report with {len(articles)} articles...")
    summarizer.generate_docx(articles, local_path, title=title)
    
    # Upload to GCS
    gcs_blob_path = f"reports/{filename}"
    blob = gcs._bucket.blob(gcs_blob_path)
    blob.upload_from_filename(str(local_path))
    gcs_path = f"gs://{gcs.bucket_name}/{gcs_blob_path}"
    print(f"   ✅ Uploaded to {gcs_path}")
    
    return local_path, gcs_path


def send_topic_email(
    email_client: EmailClient,
    recipients: List[str],
    topic: str,
    doc_path: Path,
    start_date: datetime,
    end_date: datetime,
    article_count: int,
) -> bool:
    """Send email with the topic report attached."""
    subject = f"[Regulatory Intelligence] {topic} Report - {end_date.strftime('%b %d, %Y')}"
    
    body_html = f"""
    <html>
    <body>
    <h2>{topic} - Regulatory Intelligence Briefing</h2>
    <p>Please find attached the regulatory intelligence report for <strong>{topic}</strong>.</p>
    <p><strong>Period:</strong> {start_date.strftime('%B %d, %Y')} - {end_date.strftime('%B %d, %Y')}</p>
    <p><strong>Articles Reviewed:</strong> {article_count}</p>
    <br>
    <p>This report was automatically generated by the Regulatory Intelligence system.</p>
    </body>
    </html>
    """
    
    return email_client.send_report(
        to_emails=recipients,
        subject=subject,
        body_html=body_html,
        attachment_path=doc_path,
    )


def main():
    parser = argparse.ArgumentParser(description="Generate and email topic reports from GCS")
    parser.add_argument("--days", type=int, default=7,
                        help="Number of days back to gather results (default: 7)")
    parser.add_argument("--no-email", action="store_true",
                        help="Skip sending emails (just generate reports)")
    args = parser.parse_args()
    
    days_back = args.days
    skip_email = args.no_email
    
    print("=" * 60)
    print("📄 REPORT GENERATION")
    print(f"   Days back: {days_back}")
    print(f"   Email: {'disabled' if skip_email else 'enabled'}")
    print("=" * 60)
    
    # Initialize clients
    print("\n[Init] Connecting to GCS...")
    gcs = GCSClient()
    
    print("[Init] Loading database...")
    db = DBClient(auto_sync=True)
    
    print("[Init] Initializing summarizer...")
    summarizer = ReportSummarizer()
    
    email_client = None
    if not skip_email:
        print("[Init] Initializing email client...")
        try:
            email_client = EmailClient()
        except ValueError as e:
            print(f"   ⚠ Email disabled: {e}")
            skip_email = True
    
    # Calculate date range
    end_date = datetime.utcnow()
    start_date = end_date - timedelta(days=days_back)
    
    # List recent results
    print(f"\n[1/3] Listing results from last {days_back} days...")
    results_by_topic = list_recent_results(gcs, days_back=days_back)
    
    if not results_by_topic:
        print("   ⚠ No results found in GCS for the specified period")
        return
    
    print(f"   Found {len(results_by_topic)} topics with results")
    for topic, paths in results_by_topic.items():
        print(f"      - {topic}: {len(paths)} file(s)")
    
    # Process each topic
    print(f"\n[2/3] Generating reports...")
    reports_generated = []
    
    for topic, blob_paths in results_by_topic.items():
        print(f"\n{'=' * 50}")
        print(f"📁 {topic}")
        print("=" * 50)
        
        # Load articles
        print(f"   Loading articles from {len(blob_paths)} file(s)...")
        articles = load_articles_from_gcs(gcs, blob_paths)
        
        if not articles:
            print(f"   ⚠ No articles found for {topic}")
            continue
        
        print(f"   Found {len(articles)} unique articles")
        
        # Filter to high-relevance articles only
        high_relevance = [a for a in articles if (a.relevance_score or 0) >= 6]
        print(f"   High relevance (≥6): {len(high_relevance)} articles")
        
        if not high_relevance:
            print(f"   ⚠ No high-relevance articles to summarize")
            continue
        
        # Generate report and upload to GCS
        try:
            with tempfile.TemporaryDirectory() as temp_dir:
                doc_path, gcs_path = generate_topic_report(
                    summarizer=summarizer,
                    gcs=gcs,
                    topic=topic,
                    articles=high_relevance,
                    start_date=start_date,
                    end_date=end_date,
                    temp_dir=Path(temp_dir),
                )
                reports_generated.append((topic, doc_path, gcs_path, len(high_relevance)))
        except Exception as e:
            print(f"   ❌ Report generation failed: {e}")
    
    # Send emails (need to re-download from GCS since temp files are gone)
    if not skip_email and email_client and reports_generated:
        print(f"\n[3/3] Sending emails...")
        with tempfile.TemporaryDirectory() as temp_dir:
            for topic, _, gcs_path, article_count in reports_generated:
                # Get subscribed users for this topic
                users = db.get_users_by_topic(topic)
                if not users:
                    print(f"   ⚠ No users subscribed to {topic}, skipping email")
                    continue
                
                recipients = [u.email for u in users]
                print(f"   Sending {topic} to {len(recipients)} recipient(s)...")
                
                # Download report from GCS for email attachment
                blob_path = gcs_path.replace(f"gs://{gcs.bucket_name}/", "")
                blob = gcs._bucket.blob(blob_path)
                local_path = Path(temp_dir) / Path(blob_path).name
                blob.download_to_filename(str(local_path))
                
                success = send_topic_email(
                    email_client=email_client,
                    recipients=recipients,
                    topic=topic,
                    doc_path=local_path,
                    start_date=start_date,
                    end_date=end_date,
                    article_count=article_count,
                )
                if success:
                    print(f"   ✅ Email sent for {topic}")
                else:
                    print(f"   ❌ Email failed for {topic}")
    elif skip_email:
        print(f"\n[3/3] Skipping email (--no-email flag)")
    
    # Summary
    print("\n" + "=" * 60)
    print("📊 SUMMARY")
    print("=" * 60)
    print(f"   Topics processed: {len(results_by_topic)}")
    print(f"   Reports generated: {len(reports_generated)}")
    for topic, _, gcs_path, count in reports_generated:
        print(f"      - {topic}: {count} articles → {gcs_path}")
    
    print("\n✅ Report generation complete!")


if __name__ == "__main__":
    main()
